### ISSUE TITLE
Connection timeout

### ISSUE THREAD

**Issue by queglay** [zugdud/openvpn_aws_cloudformation#1]
I get "connection timeout" on two different macs running open vpn connect when attempting to connect using the .ovpn file from s3 after running the cloudformation template. (macos 10.13.6 & 10.14.1)

I have been able to successfully connect to other open vpn instances in AWS (like the open vpn ami) using these mac's as well, so I'm wondering what the next steps might be to troubleshoot.

I can succesfuly ping the insstance using the public ip if I open up icmp on the security group.

Thanks for any help, this is a very cool project you've built here!

**Comment by zugdud** [comment]
Greetings, apologies for the late reply. I tried using the OpenVPN connect client on my mac and it also didn't work. I believe it is because this client has some dependency with features that are part of the OpenVPN Access Server offering, I'm not sure if it's intended to be used by vanilla openvpn deployments. For Mac I recommend an open source client program called Tunnelblick which has been working great for me, link here: https://tunnelblick.net/
